// Generated by scripts/build_api_catalog.py; edit the reference to regenerate.
const API_OPERATIONS = [
  {
    "method": "GET",
    "path": "/signals",
    "label": "List latest signal values",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần read cho GET, write cho PUT/POST; full bao gồm read/write. X-Dev-Mode có thể bypass kiểm tra profile."
  },
  {
    "method": "GET",
    "path": "/signals/available",
    "label": "List all available signals with metadata",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần read cho GET, write cho PUT/POST; full bao gồm read/write. X-Dev-Mode có thể bypass kiểm tra profile."
  },
  {
    "method": "GET",
    "path": "/signals/{signal_name}",
    "label": "Get latest value for one signal",
    "body": null,
    "query": "",
    "parameters": [
      {
        "name": "signal_name",
        "where": "path",
        "kind": "string",
        "required": true,
        "limits": ""
      }
    ],
    "auth": "API key khi authentication bật. Profile cần read cho GET, write cho PUT/POST; full bao gồm read/write. X-Dev-Mode có thể bypass kiểm tra profile."
  },
  {
    "method": "PUT",
    "path": "/signals/{signal_name}",
    "label": "Write value to signal (CAN write)",
    "body": {
      "value": 0
    },
    "query": "",
    "parameters": [
      {
        "name": "signal_name",
        "where": "path",
        "kind": "string",
        "required": true,
        "limits": ""
      }
    ],
    "auth": "API key khi authentication bật. Profile cần read cho GET, write cho PUT/POST; full bao gồm read/write. X-Dev-Mode có thể bypass kiểm tra profile."
  },
  {
    "method": "GET",
    "path": "/signals/{signal_name}/history",
    "label": "Query signal history from DB",
    "body": null,
    "query": "start=1789600000&end=1789603600&limit=100&offset=0",
    "parameters": [
      {
        "name": "signal_name",
        "where": "path",
        "kind": "string",
        "required": true,
        "limits": ""
      },
      {
        "name": "start",
        "where": "query",
        "kind": "number / null",
        "required": false,
        "limits": ""
      },
      {
        "name": "end",
        "where": "query",
        "kind": "number / null",
        "required": false,
        "limits": ""
      },
      {
        "name": "limit",
        "where": "query",
        "kind": "integer",
        "required": false,
        "limits": "default=100; minimum=1; maximum=10000"
      },
      {
        "name": "offset",
        "where": "query",
        "kind": "integer",
        "required": false,
        "limits": "default=0; minimum=0"
      }
    ],
    "auth": "API key khi authentication bật. Profile cần read cho GET, write cho PUT/POST; full bao gồm read/write. X-Dev-Mode có thể bypass kiểm tra profile."
  },
  {
    "method": "POST",
    "path": "/signals/batch_update",
    "label": "Write multiple writable signals simultaneously (batch)",
    "body": {
      "signals": [
        {
          "signal_name": "ABL_FL_RetractRequest",
          "value": 0
        },
        {
          "signal_name": "ABL_FR_RetractRequest",
          "value": 0
        }
      ]
    },
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần read cho GET, write cho PUT/POST; full bao gồm read/write. X-Dev-Mode có thể bypass kiểm tra profile."
  },
  {
    "method": "GET",
    "path": "/config",
    "label": "List all signal configurations",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Không có kiểm tra quyền profile bổ sung trên route này."
  },
  {
    "method": "GET",
    "path": "/config/signal/{signal_name}",
    "label": "Get config for one signal",
    "body": null,
    "query": "",
    "parameters": [
      {
        "name": "signal_name",
        "where": "path",
        "kind": "string",
        "required": true,
        "limits": ""
      }
    ],
    "auth": "API key khi authentication bật. Không có kiểm tra quyền profile bổ sung trên route này."
  },
  {
    "method": "PATCH",
    "path": "/config/signal/{signal_name}",
    "label": "Update signal config",
    "body": {
      "unit": "",
      "min_value": 0,
      "max_value": 12,
      "widget_type": "slider",
      "writable": true
    },
    "query": "",
    "parameters": [
      {
        "name": "signal_name",
        "where": "path",
        "kind": "string",
        "required": true,
        "limits": ""
      }
    ],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode."
  },
  {
    "method": "GET",
    "path": "/config/processor",
    "label": "Get processor config",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Không có kiểm tra quyền profile bổ sung trên route này."
  },
  {
    "method": "POST",
    "path": "/config/processor",
    "label": "Update processor config",
    "body": {
      "max_queue_size": 10000,
      "queue_policy": "drop_oldest"
    },
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode."
  },
  {
    "method": "GET",
    "path": "/config/system",
    "label": "Get system config and field update policy",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Không có kiểm tra quyền profile bổ sung trên route này."
  },
  {
    "method": "PATCH",
    "path": "/config/system",
    "label": "Patch system config without dropping unrelated fields",
    "body": {
      "reader": {
        "stale_threshold_sec": 30
      }
    },
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode."
  },
  {
    "method": "GET",
    "path": "/config/system/backups",
    "label": "List fixed-path system config backups",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Không có kiểm tra quyền profile bổ sung trên route này."
  },
  {
    "method": "POST",
    "path": "/config/system/backups",
    "label": "Back up system config",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode."
  },
  {
    "method": "POST",
    "path": "/config/system/backups/{backup_id}/restore",
    "label": "Restore a system config backup",
    "body": null,
    "query": "",
    "parameters": [
      {
        "name": "backup_id",
        "where": "path",
        "kind": "string",
        "required": true,
        "limits": ""
      }
    ],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode."
  },
  {
    "method": "POST",
    "path": "/config/system/reset",
    "label": "Reset system config from the fixed project template",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode."
  },
  {
    "method": "POST",
    "path": "/config/system/reload",
    "label": "Re-apply live fields from the system config file",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode."
  },
  {
    "method": "GET",
    "path": "/config/general",
    "label": "Get full application config",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Không có kiểm tra quyền profile bổ sung trên route này."
  },
  {
    "method": "PATCH",
    "path": "/config/general",
    "label": "Patch application config (partial)",
    "body": {
      "reader": {
        "stale_threshold_sec": 30
      }
    },
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode."
  },
  {
    "method": "POST",
    "path": "/config/general/reset",
    "label": "Reset application config to defaults",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode."
  },
  {
    "method": "GET",
    "path": "/adaptive_restraint/available",
    "label": "Get all available options for adaptive restraint filters",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/adaptive_restraint/chart_info",
    "label": "Get statistic and chart information for adaptive restraint systems",
    "body": null,
    "query": "System=fusion&System=camera&Age=35y&RawData=false",
    "parameters": [
      {
        "name": "System",
        "where": "query",
        "kind": "array<string>",
        "required": false,
        "limits": ""
      },
      {
        "name": "Age",
        "where": "query",
        "kind": "array<string>",
        "required": false,
        "limits": ""
      },
      {
        "name": "Seatbelt",
        "where": "query",
        "kind": "array<string>",
        "required": false,
        "limits": ""
      },
      {
        "name": "Velocity",
        "where": "query",
        "kind": "array<number>",
        "required": false,
        "limits": ""
      },
      {
        "name": "Weight",
        "where": "query",
        "kind": "array<number>",
        "required": false,
        "limits": ""
      },
      {
        "name": "Height",
        "where": "query",
        "kind": "array<number>",
        "required": false,
        "limits": ""
      },
      {
        "name": "Distance",
        "where": "query",
        "kind": "array<number>",
        "required": false,
        "limits": ""
      },
      {
        "name": "RawData",
        "where": "query",
        "kind": "boolean",
        "required": false,
        "limits": "default=true"
      }
    ],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/system/info",
    "label": "Get project & system information",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/system/health",
    "label": "Health check",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/system/ready",
    "label": "Readiness probe (for container/systemd)",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/system/metrics",
    "label": "CarPC resource information (CPU, RAM, disk, queue, heap…)",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "POST",
    "path": "/system/can/retry",
    "label": "Retry CAN connections",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key thực + `X-Dev-Mode: true`."
  },
  {
    "method": "POST",
    "path": "/system/reboot",
    "label": "Reboot Car-HMI service",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key thực + `X-Dev-Mode: true`."
  },
  {
    "method": "GET",
    "path": "/api/restraints/match",
    "label": "Find best-matching restraint video for crash conditions",
    "body": null,
    "query": "weight=75&height=175&crash_severity=40&seatbelt_system=SLL&seat=fl&seat_x_mm=100",
    "parameters": [
      {
        "name": "weight",
        "where": "query",
        "kind": "number",
        "required": true,
        "limits": ""
      },
      {
        "name": "height",
        "where": "query",
        "kind": "number",
        "required": true,
        "limits": ""
      },
      {
        "name": "crash_severity",
        "where": "query",
        "kind": "integer",
        "required": true,
        "limits": ""
      },
      {
        "name": "seatbelt_system",
        "where": "query",
        "kind": "string",
        "required": true,
        "limits": ""
      },
      {
        "name": "seat",
        "where": "query",
        "kind": "string",
        "required": false,
        "limits": "default=\"fl\""
      },
      {
        "name": "seat_x_mm",
        "where": "query",
        "kind": "number / null",
        "required": false,
        "limits": ""
      }
    ],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/api/restraints/video/{filename}",
    "label": "Stream a video file from the media directory",
    "body": null,
    "query": "",
    "parameters": [
      {
        "name": "filename",
        "where": "path",
        "kind": "string",
        "required": true,
        "limits": ""
      }
    ],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/api/camera/stream",
    "label": "Proxy live MJPEG stream from the vehicle camera",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/api/camera/status",
    "label": "Camera stream proxy status",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/api/devmode/catalog",
    "label": "Dev Mode signal families and selectable states",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Route không bắt buộc X-Dev-Mode hoặc kiểm tra profile; các thao tác khóa/status cần X-Client-Id."
  },
  {
    "method": "GET",
    "path": "/api/devmode/status",
    "label": "Current Dev Mode seat locks",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Route không bắt buộc X-Dev-Mode hoặc kiểm tra profile; các thao tác khóa/status cần X-Client-Id."
  },
  {
    "method": "POST",
    "path": "/api/devmode/seats/select",
    "label": "Select seats for Dev Mode (locks other sections out)",
    "body": {
      "seats": {
        "fl": true,
        "fr": false
      },
      "block_timeout_sec": 60
    },
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Route không bắt buộc X-Dev-Mode hoặc kiểm tra profile; các thao tác khóa/status cần X-Client-Id."
  },
  {
    "method": "POST",
    "path": "/api/devmode/exit",
    "label": "Leave Dev Mode and release all seat locks of this section",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Route không bắt buộc X-Dev-Mode hoặc kiểm tra profile; các thao tác khóa/status cần X-Client-Id."
  },
  {
    "method": "POST",
    "path": "/api/devmode/signals",
    "label": "Apply one signal family to several seats at once",
    "body": {
      "signal_name": "ABL_RetractRequest",
      "value": 0,
      "seats": {
        "fl": true
      },
      "block_timeout_sec": 60
    },
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Route không bắt buộc X-Dev-Mode hoặc kiểm tra profile; các thao tác khóa/status cần X-Client-Id."
  },
  {
    "method": "GET",
    "path": "/api/info",
    "label": "Get project & system information",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/api/health",
    "label": "Health check",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/api/ready",
    "label": "Readiness probe (for container/systemd)",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "GET",
    "path": "/api/metrics",
    "label": "CarPC resource information (CPU, RAM, disk, queue, heap…)",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "Không có dependency API key trên route này."
  },
  {
    "method": "POST",
    "path": "/api/can/retry",
    "label": "Retry CAN connections",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key thực + `X-Dev-Mode: true`."
  },
  {
    "method": "POST",
    "path": "/api/reboot",
    "label": "Reboot Car-HMI service",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key thực + `X-Dev-Mode: true`."
  },
  {
    "method": "GET",
    "path": "/api/profiles",
    "label": "List all profiles",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Không có kiểm tra quyền profile bổ sung trên route này."
  },
  {
    "method": "GET",
    "path": "/api/profile/sessions",
    "label": "List client active-profile sessions",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần read hoặc X-Dev-Mode."
  },
  {
    "method": "POST",
    "path": "/api/profile/heartbeat",
    "label": "Heartbeat for client profile session",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Không có kiểm tra quyền profile bổ sung trên route này."
  },
  {
    "method": "POST",
    "path": "/api/profile/offline",
    "label": "Mark client profile session offline",
    "body": null,
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Không có kiểm tra quyền profile bổ sung trên route này."
  },
  {
    "method": "GET",
    "path": "/api/profile",
    "label": "Get profile by name (or active profile)",
    "body": null,
    "query": "name=demo",
    "parameters": [
      {
        "name": "name",
        "where": "query",
        "kind": "string / null",
        "required": false,
        "limits": ""
      }
    ],
    "auth": "API key khi authentication bật. Không có kiểm tra quyền profile bổ sung trên route này."
  },
  {
    "method": "POST",
    "path": "/api/profile",
    "label": "Create new profile",
    "body": {
      "name": "demo",
      "signals": [
        {
          "name": "COM_Status_ElkCan",
          "permission": [
            "read"
          ]
        },
        {
          "name": "ABL_FL_RetractRequest",
          "permission": [
            "read",
            "write"
          ]
        }
      ],
      "exinfo": {
        "label": "Demo"
      },
      "description": "Demo profile"
    },
    "query": "name=demo",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode; tạo profile đầu tiên cho phép bootstrap khi chưa có profile."
  },
  {
    "method": "PUT",
    "path": "/api/profile",
    "label": "Update profile (optimistic lock)",
    "body": {
      "name": "demo",
      "signals": [
        {
          "name": "COM_Status_ElkCan",
          "permission": [
            "read"
          ]
        }
      ],
      "section_id": "012345abcdef",
      "exinfo": {},
      "description": "Demo profile"
    },
    "query": "name=demo",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode; tạo profile đầu tiên cho phép bootstrap khi chưa có profile."
  },
  {
    "method": "PUT",
    "path": "/api/profile/active",
    "label": "Set active profile",
    "body": {
      "name": "demo"
    },
    "query": "",
    "parameters": [],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode; tạo profile đầu tiên cho phép bootstrap khi chưa có profile."
  },
  {
    "method": "DELETE",
    "path": "/api/profile/{name}",
    "label": "Delete profile",
    "body": null,
    "query": "",
    "parameters": [
      {
        "name": "name",
        "where": "path",
        "kind": "string",
        "required": true,
        "limits": ""
      }
    ],
    "auth": "API key khi authentication bật. Profile cần full hoặc X-Dev-Mode; tạo profile đầu tiên cho phép bootstrap khi chưa có profile."
  }
];
