services:
  - type: web
    name: car-hmi-api-demo
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /api/info
