"""Generate demo operation presets from the Vietnamese API reference."""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
reference = (root / 'docs/api_reference_vi.md').read_text()
operations = []
for match in re.finditer(r'^### `(GET|POST|PUT|PATCH|DELETE) ([^`]+)`\n(.*?)(?=^### |^## |\Z)', reference, re.M | re.S):
    method, path, section = match.groups()
    request_section = section.split('Response thành công:')[0]
    body_match = re.search(r'```json\n(.*?)\n```', request_section, re.S)
    body = json.loads(body_match.group(1)) if body_match else None
    query = re.search(r'\$BASE[^"\n]*\?([^"\n]*)', request_section)
    parameters = []
    for parameter in re.finditer(r'^\| `([^`]+)` \| (path|query) \| ([^|]+) \| ([^|]+) \| ([^|]*)\|', section, re.M):
        name, where, kind, required, limits = parameter.groups()
        parameters.append(dict(name=name, where=where, kind=kind.strip(), required=required.strip() == 'Có', limits=limits.strip()))
    operations.append(dict(method=method, path=path, label=section.strip().splitlines()[0], body=body, query=query.group(1) if query else '', parameters=parameters, auth=re.search(r'^Auth: (.*)', section, re.M).group(1)))
(root / 'js/api-catalog.js').write_text('// Generated by scripts/build_api_catalog.py; edit the reference to regenerate.\nconst API_OPERATIONS = ' + json.dumps(operations, ensure_ascii=False, indent=2) + ';\n')
print(f'Generated {len(operations)} HTTP operation presets')
